### ISSUE TITLE
Change in size of compressed arrays between versions

### ISSUE THREAD

**Issue by ntolia** [xerial/snappy-java#106]
I am running a test that compares org.xerial.snappy across versions. Now, till version 1.0.5.4, the output of ```Snappy.compress(new byte[65536])``` created a byte array of 3079 elements. However, when I upgraded to version 1.1.1.7, I noticed that the same code now generates an array of 3077 elements. I would not have expected this to change. In fact, the output of 1.0.5.4 matches other implementations such as https://github.com/dain/snappy while 1.1.1.7 does not. I also run into similar errors for other array sizes including ```new byte[32769]```. Happy to run more tests if it helps.

**Comment by xerial** [comment]
There might have some changes in the snappy's implementation. Please check here: https://github.com/google/snappy/blob/master/ChangeLog

But in practice, could you tell me why decreasing the compressed size matters?

**Comment by ntolia** [comment]
Will check but it looks like there were snappy upgrades between 1.0.5.x and 1.1.x.x.

Decreasing compressed size does not generally matter but the test in this case is using different sizes as a potential warning in case there has been a break in compatibility. That is, a compressed array from an older version of the library would not be read correctly by a newer version (or the inverse situation). Given that we have run into bugs like #100 here, I did want to report/check if this was a known upstream change that did not break compatibility or something in this library.

**Comment by xerial** [comment]
As long as Snappy.compress and uncompress are used, #100 is not related since it happened when using SnappyOutputStream.  

As far as I know, there is no backward incompatible change in the format level between 1.0.5.x and 1.1.x, so even if the compressed size has slightly changed, data can be read correctly in both version.

**Comment by bokken** [comment]
This (https://github.com/google/snappy/commit/27a0cc394950ebdad2e8d67322f0862835b10bd9) is the change in snappy which resulted in a change in compression size in release 1.1.

**Comment by xerial** [comment]
Thanks. So it's not a backward incompatible change. Now let me close the ticket.

**Comment by ntolia** [comment]
Thanks for all the help folks. Really appreciated.
