### ISSUE TITLE
Magic header is not correct according to standard

### ISSUE THREAD

**Issue by thingmarius** [xerial/snappy-java#115]
According to the official format description from Google, the magic header for snappy streams should be the following: 

> 4.1. Stream identifier (chunk type 0xff)
> 
> The stream identifier is always the first element in the stream.
> It is exactly six bytes long and contains "sNaPpY" in ASCII. This means that
> a valid Snappy framed stream always starts with the bytes
> 
>   0xff 0x06 0x00 0x00 0x73 0x4e 0x61 0x50 0x70 0x59
> 
> The stream identifier chunk can come multiple times in the stream besides
> the first; if such a chunk shows up, it should simply be ignored, assuming
> it has the right length and contents. This allows for easy concatenation of
> compressed files without the need for re-framing.

**Comment by xerial** [comment]
snappy-java was developed before this framed format was born. For compatibility SnappyOutputStream uses its own format. If you need to use the framed format, use SnappyFramedOutputStream.

**Comment by TJC** [comment]
So, we spent quite a while trying to track down the incompatibility between the python-snappy library, and the snappy-java library, before eventually coming across this. 

Would it be possible to put a warning or note in the README here, to explain the situation?
It could save other people from hitting this same issue.

**Comment by xerial** [comment]
@TJC Yes. Here are some notes on README for this compatibility: https://github.com/xerial/snappy-java#compatibility-notes

PR to README would be easier for me to fix the documentation to notify users about this issue.
