### ISSUE TITLE
Support amd64 alias in addition to x86_64

### ISSUE THREAD

**Issue by avianey** [xerial/snappy-java#116]
OSGI rely on os.arch properties wich replies "amd64" sometimes and fails to load native dependencies from the MANIFEST... (should be the same for x64)

**Comment by avianey** [comment]
Is it possible to push a 1.1.1.8 for this ?
Regards

**Comment by xerial** [comment]
version name 1.1.2-RC3 works for you?

**Comment by xerial** [comment]
Deployed 1.1.2-RC3 with this fix.

**Comment by avianey** [comment]
thx

**Comment by xerial** [comment]
Yes.
http://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.2-RC3/

**Comment by xerial** [comment]
@avianey 
If you find this problem fixed with 1.1.2-RC3, please close this ticket.
Thanks.

**Comment by avianey** [comment]
can't test for now, we removed snappy from the client and we don't have amd servers to reproduce now

**Comment by xerial** [comment]
I'll close this issue. Please re-open it if you find any problem.
