### ISSUE TITLE
Snappy for AIX - ppc (32 bit) - New Feature

### ISSUE THREAD

**Issue by mohanaugust** [xerial/snappy-java#123]
I am trying to use snappy.jar in AIX 32 bit environment.In this system i do not have rights to install gmake (to build snappy from git). I checked snappy.jar and i see only org/xerial/snappy/native/AIX/ppc64 . I couldnt see one for AIX/ppc. It would be of great help if you have "libsnappyjava.a" for AIX ppc (32 bit) also in the snappy.jar

**Comment by xerial** [comment]
I'll seek a way for cross compiling ppc32 binary.

**Comment by bryanpkc** [comment]
If you haven't started on this, I can probably help; I have access to AIX hardware.

**Comment by xerial** [comment]
Thanks!
