### ISSUE TITLE
Build jar for windows and linux only

### ISSUE THREAD

**Issue by thanhdowisc** [xerial/snappy-java#126]
Hi,

I just want to build the jar file that can work for windows and Linux only, how could I do that?

Thanks

**Comment by thanhdowisc** [comment]
To clarify, I want to build a cross-platform jar for linux64 and win64. Would the following command work?
```
make win64 linux-aarch64
make package
```

**Comment by xerial** [comment]
Just remove unnecessary native libraries from src/main/resources folder, then run make package again.

**Comment by thanhdowisc** [comment]
Thanks!
