### ISSUE TITLE
Glibc version of native library

### ISSUE THREAD

**Issue by thanhdowisc** [xerial/snappy-java#127]
Hi guys, 

Just curious what glibc version the native binary for linux was built? And what is the recommended version for this if I want to build the snappy jar on my own?

I compiled the snappy jar under ubuntu 64 bit. and use the Jar in in a MR job but the job failed because of this error:

/lib64/libc.so.6: version `GLIBC_2.14' not found

Apparently, i built the native snappy with GLIBC 2.14 but the cluster I ran MR job does has an older version of glibc.

Thanks,

**Comment by xerial** [comment]
To build snappy-java for linux, I am using an older version of glibc (2.5, with CentOS 5). glibc is backward compatible, so there is no problem in using quite an old version of glibc in building snappy-java.

**Comment by xerial** [comment]
You can check glibc version with `ldd --version` command.
