### ISSUE TITLE
Very Generic Error

### ISSUE THREAD

**Issue by KenBeanNet** [xerial/snappy-java#130]
Anyone able to help me track down a snappy error?  I am only getting one very vague error.

[code]
Faulting application name: java.exe, version: 8.0.660.17, time stamp: 0x56147e23
Faulting module name: snappy-1.1.2-ac58c1f7-729b-447d-b7ef-006cbb5b1ab3-snappyjava.dll, version: 0.0.0.0, time stamp: 0x525f897b
Exception code: 0x40000015
Fault offset: 0x000000000000d391
Faulting process id: 0x9994
Faulting application start time: 0x01d13c1c042073b7
Faulting application path: C:\jdk\bin\java.exe
Faulting module path: C:\Windows\Temp\snappy-1.1.2-ac58c1f7-729b-447d-b7ef-006cbb5b1ab3-snappyjava.dll
Report Id: 802645d3-a80f-11e5-80bf-7824af82661f
Faulting package full name: 
Faulting package-relative application ID: 
[/code]

**Comment by xerial** [comment]
Do you have any stack trace or the data to reproduce this issue?

**Comment by KenBeanNet** [comment]
I ended up upgrading from J8U65 to 66 to resolve the issue.  You can close I guess?

**Comment by xerial** [comment]
OK. Let me close this ticket. Thanks.
