### ISSUE TITLE
New release incorporating AArch64 support

### ISSUE THREAD

**Issue by AGSaidi** [xerial/snappy-java#134]
With the aarch64 support added in PR #133 it would be great to have a new release of snappy-java so other projects can pick-up support for AArch64. What is the process for creating a new release?

**Comment by xerial** [comment]
Currently I haven't tried to collecting native libraries for 1.1.3 for various platforms. 

If you can submit another PR and a native library based on https://github.com/xerial/snappy-java/releases/tag/1.1.2.1, I can release a new version 1.1.2.2 with AArch64 support.

**Comment by xerial** [comment]
Here is the target branch to create a PR: https://github.com/xerial/snappy-java/tree/1.1.2.x

**Comment by jayminraval** [comment]
@xerial Should one just follow the steps listed on the main github page, to build the native library for AArch64?

**Comment by soumitrachatterjee** [comment]
I have raised a pull request for the binary for the 1.1.2.x branch as requested above.

**Comment by xerial** [comment]
Deployed snappy-java 1.1.2.2, which will be available soon from the Maven central.
