### ISSUE TITLE
Branch 1.1.2.x fails to build off-the-shelf

### ISSUE THREAD

**Issue by soumitrachatterjee** [xerial/snappy-java#136]
Looks like a broken dependency on the download link for snappy:

```
$ make
curl -otarget/snappy-1.1.2.tar.gz http://snappy.googlecode.com/files/snappy-1.1.2.tar.gz
```

The above URL does not seem to be valid.

**Comment by xerial** [comment]
Yeah. The above url no longer exists since Google code has terminated the service and snappy repository has moved to github. USE_GIT flag should be the default here: https://github.com/xerial/snappy-java/blob/master/Makefile#L19

**Comment by xerial** [comment]
Now that we are moving to 1.1.4, we no longer maintain 1.1.2
