### ISSUE TITLE
Depend on Snappy 1.1.3 as that seems to be the only version you can download

### ISSUE THREAD

**Issue by mnd999** [xerial/snappy-java#141]
I have somehow ended up as the freebsd-ports maintainer of snappy-java and I'm looking into the feasibility of bringing it up to date.

Since the githib move, Snappy 1.1.3 seems to be the only version available. Can snappy-java depend on that?

**Comment by xerial** [comment]
Hi, development of snappy-java 1.1.3, which is based on snappy 1.1.3, is now in-progress state. 

If you care about the source code availability, snappy-1.1.2 also exists at https://github.com/google/snappy/commit/1ff9be9b8fafc8528ca9e055646f5932aa5db9c4

**Comment by xerial** [comment]
A fix is on going at #151
