### ISSUE TITLE
Build error on mac x86 platform

### ISSUE THREAD

**Issue by xerial** [xerial/snappy-java#144]
This is caused by migrating to 1.1.3, which build native libraries based on google:snappy Github repo. We may need to fix their automake scripts.

**Comment by mcapavan** [comment]
unable to build on my Mac OS X EI Capitan v 10.11.5. The following is the error I have received.

Makefile.am:4:   while processing Libtool library 'libsnappy.la'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
configure.ac:42: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:44: error: possibly undefined macro: AC_MSG_FAILURE
make: *** [target/snappy-git-extracted.log] Error 1

**Comment by mcapavan** [comment]
My issue is resolved after I install  pkg-config (brew install pkg-config)

**Comment by xerial** [comment]
That is good to know.

**Comment by xerial** [comment]
From 1.1.3 we will drop the support for Mac OS X 32bit  (x86), since it's been already 8 years since the last Mac OS (Snow Leopard) which supports x86. Let me close the issue.
