### ISSUE TITLE
Error for /dataflow org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null

### ISSUE THREAD

**Issue by SUdheerAki** [xerial/snappy-java#146]
Hi All,

I am using pipelone code to read a file from Cloud storage.

Code : 

DataflowPipelineOptions options = PipelineOptionsFactory.create().as(DataflowPipelineOptions.class);
        options.setRunner(BlockingDataflowPipelineRunner.class);
        options.setProject("projectId");
            options.setStagingLocation("StagingPath");

```
    //PipelineOptions options = PipelineOptionsFactory.create();
    // Then create the pipeline.
    Pipeline p = Pipeline.create(options);
        PCollection<String> lines = p.apply(TextIO.Read.named("ReadDataFromStorage").from("source_Path"));
```

When am running from local eclipse am able to read a file.

But when i deployed to App engine i am getting below error.I am using snappy-java-1.1.2.1.jar.Please see the error below and help me ASAP.

**Error for /dataflow
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null
    at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:159)
    at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
    at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:97)
    at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:89)
    at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:79)
    at com.google.cloud.dataflow.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:49)
    at com.google.cloud.dataflow.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:84)
    at com.google.cloud.dataflow.sdk.io.Read$Bounded.<init>(Read.java:108)
    at com.google.cloud.dataflow.sdk.io.Read$Bounded.<init>(Read.java:103)
    at com.google.cloud.dataflow.sdk.io.Read.from(Read.java:62)
    at com.google.cloud.dataflow.sdk.io.TextIO$Read$Bound.apply(TextIO.java:319)**

**Comment by xerial** [comment]
@SUdheerAki 
It depends on your OS and CPU type. Let us know this information by running the following code:
https://github.com/xerial/snappy-java/blob/c975c274953fe39c2975987dde3958bdc4359574/src/main/java/org/xerial/snappy/OSInfo.java

**Comment by manuzhang** [comment]
I have run into the same problem on `Mac/x86_64`

**Comment by manuzhang** [comment]
sorry, it's my own problem where an old version of snappy-java exists on classpath

**Comment by faridghar** [comment]
How were you able to fix this? I'm having the same problem when my GAE cron job tries to execute a cloud dataflow pipeline.

**Comment by manuzhang** [comment]
I checked my classpath and found an old version of snappy-java.

**Comment by ovjy** [comment]
@faridghar where you able to resolve your issue? me too having the same problem

**Comment by ovjy** [comment]
@SUdheerAki @manuzhang are you guys starting dataflow job from app engine? are you able to resolve this issue?

**Comment by mhdirkse** [comment]
In my company we can run dataflows from AppEngine. To do this, we had to take into account that App Engine nodes do not have snappy installed. We got around this by modifying the dataflow SDK not to use snappy. This modification was in a jar containing a modified version of com.google.cloud.dataflow.sdk.util.SerializableUtils say patched.jar.

To ensure that the modified class is used instead of the original dataflow sdk version, we configured appengine-web.xml as follows:

<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
  ...
  <class-loader-config>
    <priority-specifier filename="patched.jar"/>
  </class-loader-config>
  ...
</appengine-web-app>

**Comment by faridghar** [comment]
What I did is just switched to GAE flexible environment
<https://cloud.google.com/appengine/docs/flexible/>. This environment
allows the dataflow SDK to use snappy.

**Comment by ovjy** [comment]
@faridghar I tried setting "env: flex" in app.yaml; but it didn't help. Could you please share the changes you made to make it work?

**Comment by faridghar** [comment]
use mvn archetype:generate on this archetype
<https://mvnrepository.com/artifact/com.google.appengine.archetypes/appengine-flexible-archetype/0.2.0>
to
get a template GAE flexible project. Then modify it to suit your needs.
That should work.

**Comment by ovjy** [comment]
@faridghar Tx for responding so fast. I am still not able to get it running? Do you mind sharing which configuration entry controls this? in app.yaml, pom.xml or appengine-web.xml?

**Comment by ovjy** [comment]
@faridghar It worked finally. Tx for the help.

**Comment by faridghar** [comment]
Sorry for the delay. Glad you sorted it out :)
