### ISSUE TITLE
Failure when building OHC for Fedora

### ISSUE THREAD

**Issue by trepik** [xerial/snappy-java#150]
When building OHC 0.5.1 [1] for Fedora Rawhide I get this error message when running test: 
_/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-3.b16.fc26.ppc64le/jre/bin/java: symbol lookup error: /tmp/snappy-1.1.2.4-b1507e0a-52ce-40ed-ac1d-aacbe8050e27-libsnappyjava.so: undefined symbol: _ZN6snappy19MaxCompressedLengthEm_

I thought it's OHC issue so I discussed it with upstream [2] and they could not reproduce it. I inspected what is causing the problem and came to some conclusions:
- ohc 0.5.1 depends on snappy-java 1.1.1.7
- in Fedora rawhide we have snappy-java 1.1.2.4 and the build fails [3]
- in Fedora 24 we have snappy-java 1.0.5 and the build goes successfully through

Could someone look into this issue and fix snappy to be backwards compatible, or should ohc work on updating their source to depend on the newest version of snappy-java.

Thanks 

[1] https://github.com/snazy/ohc
[2] https://github.com/snazy/ohc/issues/25
[3] http://koji.fedoraproject.org/koji/taskinfo?taskID=16474248

**Comment by snazy** [comment]
I think, I understand the problem now. But it feels very difficult to get a general fix.
Recap: Installing Fedora without `snappy-java` via `yum` and building OHC works fine. But installing `snappy-java` via `yum` and building OHC fails. To be clear, it's not something related to OHC alone.

Snappy-Java bundles the native library in the release artefact. It extracts it to a temporary location and loads it from that location. However, it seems that in @trepik's case, the native library installed via `yum` is preferred.

@trepik, from the task you referenced, I assume that it's either for DataStax's Java Driver or Apache Cassandra. To make it even more complicated, Apache Cassandra uses snappy-java 1.1.1.7 - however, the Java Driver uses snappy-java 1.1.2.6.

Not sure, whether snappy-java can somehow ensure, that only the right native library is being loaded.

For reference, all three projects just use `Snappy.compress` and `Snappy.uncompress` - i.e. no streams. In the java-driver, the only class using Snappy is [this one](https://github.com/datastax/java-driver/blob/199ed15b164be36a73d85dd22cff956a4ca6670f/driver-core/src/main/java/com/datastax/driver/core/FrameCompressor.java), in OHC it is [this](https://github.com/snazy/ohc/blob/e18330130a859735d105d112d57ab718aca18697/ohc-core/src/main/java/org/caffinitas/ohc/linked/DecompressingInputChannel.java) and [this](https://github.com/snazy/ohc/blob/e18330130a859735d105d112d57ab718aca18697/ohc-core/src/main/java/org/caffinitas/ohc/linked/CompressingOutputChannel.java), in C* it is [this](https://github.com/apache/cassandra/blob/3adfd1575cc3cf81397a7d148d5b2ed768b67014/src/java/org/apache/cassandra/io/compress/SnappyCompressor.java).

If there's anything necessary in these projects to ensure that the right version is being loaded, I'd be glad to help.

**Comment by trepik** [comment]
There has to be some issue with the way that we deliver the snappy package.
I did pack the 1.1.1.7 version for OHC and run the build.
In tests I got the following error:
[https://paste.fedoraproject.org/506676/14817917/raw/](https://paste.fedoraproject.org/506676/14817917/raw/)
We have been patching the original make file, probably we're causing the issue there.
Here is the patch we're using:
[https://trepik.fedorapeople.org/tmp/snappy-java-1.1.1.7-build.patch](https://trepik.fedorapeople.org/tmp/snappy-java-1.1.1.7-build.patch)
Could you have a look and comment on it?
Thanks

**Comment by trepik** [comment]
We have figured out the problem. Snappy java was not linking to our native snappy library which caused the issue.

**Comment by rabiif** [comment]
Can someone actually post a solution instead of just describing their experience please?
