### ISSUE TITLE
Add ByteBuffer based APIs for BitShuffle

### ISSUE THREAD

**Issue by xerial** [xerial/snappy-java#155]
We need ByteBuffer based APIs for BitShuffle. For example Jetty uses ByteBuffer based data HTTP retrieval so if we can use ByteBuffer for BitShuffle as an input/output, we can avoid data copies and memory allocation. 

In addition, initialization of byte[] involves 0-filling (due to Java specification) operation and consume CPU resource.

**Comment by maropu** [comment]
Aha, I see. If nobody takes on this, I'll do.

**Comment by xerial** [comment]
Implemented in #157
