### ISSUE TITLE
Add native libraries for AIX and s390x

### ISSUE THREAD

**Issue by xerial** [xerial/snappy-java#156]
Follow-up of #151

**Comment by xerial** [comment]
@odaira To test native libraries, you need to run `make test`. If you see some errors, it means the native libraries are not properly built.

**Comment by odaira** [comment]
Understood.  Thanks!

Got some errors in `make test`....  Will work on it.  :-(

**Comment by xerial** [comment]
@odaira Here is a note for building snappy-java on s390x:
https://github.com/xerial/snappy-java/blob/master/BUILD.md#building-linux-s390s390x-binaries

If you still see errors, please share the error logs. 
Thanks.

**Comment by xerial** [comment]
At least,
```
sudo yum install java-1.7.1-ibm-devel libstdc++-static-devel
```
this step seems necessary.

**Comment by odaira** [comment]
I sent a PR to fix one of the errors. The remaining errors are from BitShuffleTest.  I was able to reproduce these problems with the original bitshuffle, so looks like bitshuffle does not work on big-endian platforms.  I'll further investigate bitshuffle.
```
[error] Test org.xerial.snappy.BitShuffleTest.bitShuffleShortArray failed: arrays first differed at element [0]; expected:<432> but was:<-257>
[info] Test org.xerial.snappy.BitShuffleTest.bitShuffleIntArray started
[error] Test org.xerial.snappy.BitShuffleTest.bitShuffleIntArray failed: arrays first differed at element [0]; expected:<432> but was:<65279>
[info] Test org.xerial.snappy.BitShuffleTest.bitShuffleFloatArray started
[error] Test org.xerial.snappy.BitShuffleTest.bitShuffleFloatArray failed: arrays first differed at element [0]; expected:<100.0> but was:<-0.04375047609210014>
[info] Test org.xerial.snappy.BitShuffleTest.bitShuffleDoubleArray started
[error] Test org.xerial.snappy.BitShuffleTest.bitShuffleDoubleArray failed: arrays first differed at element [0]; expected:<100.0> but was:<-1.2098940003240079E297>
```

**Comment by xerial** [comment]
Thanks. I've merged the PR #159 

@maropu Do you have any idea for supporting BE platform?

**Comment by maropu** [comment]
Just a guess though, this issue is related to https://github.com/kiyo-masui/bitshuffle/pull/56

**Comment by xerial** [comment]
@odaira Could you try again by using the master branch, which uses snappy-1.1.4 with bitshuffle 0.3.2, which fixes this bigendian problem?

**Comment by xerial** [comment]
done in #165 #167
