### ISSUE TITLE
UnsatisfiedLinkError: org.xerial.snappy.SnappyNative.maxCompressedLength(I)I

### ISSUE THREAD

**Issue by nratta** [xerial/snappy-java#160]
Hi ,
I am using java 6 with jboss 6.
Added snappy version :-  snappy-java-1.0.5.jar
Added jar file in build path and server's lib.

Code is working fine with standalone java program.
But it gives error while calling from JSP....
**Error :  java.lang.UnsatisfiedLinkError: org.xerial.snappy.SnappyNative.maxCompressedLength(I)I**

**Comment by nratta** [comment]
any clues    ????

**Comment by xerial** [comment]
Please use the latest version. We no longer maintin 1.0.5
