### ISSUE TITLE
snappy 1.1.4 support

### ISSUE THREAD

**Issue by mailmaldi** [xerial/snappy-java#161]
Any plans to support the newly released snappy stable release ?
https://github.com/google/snappy

**Comment by xerial** [comment]
Good to know snappy 1.1.4 is released. I will create a snapshot version first.

**Comment by xerial** [comment]
@mailmaldi Upgraded. Please try a snapshot version: https://oss.sonatype.org/content/repositories/snapshots/org/xerial/snappy/snappy-java/1.1.4-SNAPSHOT/snappy-java-1.1.4-SNAPSHOT.jar

**Comment by xerial** [comment]
done.
