### ISSUE TITLE
Class Cast Exception with SnappyCodec !!!!!!

### ISSUE THREAD

**Issue by nratta** [xerial/snappy-java#166]
Hi ,
I am using java -8 and Wildfly 10 as an application server and SnappyCodec as my codec in config file.
'JobData' is my custom class .
I am storing JobData object as a cache value.
And just trying to get back that value .......
Error : 
**java.lang.ClassCastException: com.de.integration.dataobject.JobData cannot be cast to com.de.integration.dataobject.JobData**

**But with default codec :**  No error
**My Java code : -**
public void testRedis() throws Exception {
        JobData w_RetVal = (JobData) CacheService.get(CacheConstants.CACHEKEY.ADAPTOR_CKEY_JOBNAME_JOBDATA, "SwiftRulesNonEventProcessorAdaptor");
        CacheServiceTest.put(CacheConstants.CACHEKEY.REDIS_TEST, "Key12",w_RetVal);
        long startTime1 = System.nanoTime();
        JobData w_res  =  (JobData) CacheServiceTest.get(CacheConstants.CACHEKEY.REDIS_TEST, "Key12");
		long spentTime1 = (System.nanoTime() - startTime1)/1000000;
        System.out.println("Cache Get Time: " + spentTime1);
     
        
    }
	
**My Config File : -** 

{
"singleServerConfig":{
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "address": "redis://192.168.100.166:6379"
   },
   "threads":8,
   "codec": {"class":"org.redisson.codec.SnappyCodec"},
   "nettyThreads":8
}

**Comment by xerial** [comment]
snappy-java doesn't know anything about `org.redisson.codec.SnappyCodec`.  Please ask the library provider you are using.
