### ISSUE TITLE
ppc64/libsnappyjava.so does not work on Linux/ppc64

### ISSUE THREAD

**Issue by odaira** [xerial/snappy-java#168]
ppc64/libsnappyjava.so in the master branch does not run on Linux/ppc64.

> $ ./ibm-java-ppc64-80/bin/java -cp snappy-java-1.1.4-SNAPSHOT.jar:. TestSnappy1
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.4-4d3be4f8-2ac7-46e8-adb9-59e99b9c1d52-libsnappyjava.so (/tmp/snappy-1.1.4-4d3be4f8-2ac7-46e8-adb9-59e99b9c1d52-libsnappyjava.so: ELF file data encoding not big-endian)
	at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1348)
	at java.lang.System.load(System.java:539)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
	at TestSnappy1.main(TestSnappy1.java:9)

ppc64 is a big-endian architecture, but I guess ppc64/libsnappyjava.so was built for ppc64le (little endian). For your information, there are 3 architectures in POWER Linux: ppc (32-bit big endian), ppc64 (64-bit big endian), and ppc64le (64-bit little endian).

I can provide you with native binaries for these 3 architectures, but can you also check the current build process of ppc64/libsnappyjava.so? (I guess you are using a cross-compiler on Docker, right?)

**Comment by xerial** [comment]
That's correct. The current ppc64 library was built for little endian by using a cross compiler
https://github.com/xerial/snappy-java/blob/9cf04cdd6e1781e723f928bfa55ba4c90eacc0f7/Makefile#L194

I'll fix to use os_arch value `ppc64le` for this binary.

Unfortunately docker cross compiler for ppc64 is not yet available. 
But it might be possible to prepare a cross compiler for ppc64 (big-endian) by tweaking this Dockerfile:
https://github.com/dockcross/dockcross/blob/master/linux-ppc64le/Dockerfile

**Comment by xerial** [comment]
@odaira 
Created ppc64 and ppc64le native libraries in #169. Could you try running `./sbt test` 
by using ppc64le-fix branch? 
https://github.com/xerial/snappy-java/tree/ppc64le-fix

- I'm not sure how to use cross compiler for ppc (32-bit BE). If you can provide a native lib for this, it would be great.

**Comment by odaira** [comment]
Neither of ppc64/libsnappyjava.so nor ppc64le/libsnappyjava.so worked....

ppc64:

> [info] Exception encountered when attempting to run a suite with class name: org.xerial.snappy.SnappyPerformanceTest *** ABORTED ***
[info]   java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.4-e15851c4-96ba-462d-90a4-61fbee3b047d-libsnappyjava.so (/tmp/snappy-1.1.4-e15851c4-96ba-462d-90a4-61fbee3b047d-libsnappyjava.so: ELF file data encoding not big-endian)
[info]   at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1348)
[info]   at java.lang.System.load(System.java:539)
[info]   at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
[info]   at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
[info]   at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
[info]   at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:97)
[info]   at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:89)
[info]   at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:79)
[info]   at org.xerial.snappy.SnappyPerformanceTest$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1.apply$mcV$sp(SnappyPerformanceTest.scala:35)
[info]   at org.xerial.snappy.SnappyPerformanceTest$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1.apply(SnappyPerformanceTest.scala:33)
[info]   ...

Looks like ppc64/libsnappyjava.so is still a little-endian binary:

> $ objdump -a ./src/main/resources/org/xerial/snappy/native/Linux/ppc64/libsnappyjava.so
./src/main/resources/org/xerial/snappy/native/Linux/ppc64/libsnappyjava.so:     file format elf64-little

Actually, ppc64/libsnappyjava.so and ppc64le/libsnappyjava.so are the same:

> $ cmp src/main/resources/org/xerial/snappy/native/Linux/ppc64/libsnappyjava.so src/main/resources/org/xerial/snappy/native/Linux/ppc64le/libsnappyjava.so
$

Interestingly, ppc64le/libsnappyjava.so did not work, either:

> [error] Test org.xerial.snappy.SnappyLoaderTest.loadSnappyByDiffentClassloadersInTheSameJVM failed: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.4-7ad43687-ab84-4bcf-bc71-fd4ddcdbf258-libsnappyjava.so: /tmp/snappy-1.1.4-7ad43687-ab84-4bcf-bc71-fd4ddcdbf258-libsnappyjava.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a Power PC 64-bit platform)
[error]     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[error]     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
[error]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[error]     at java.lang.Runtime.load0(Runtime.java:809)
[error]     at java.lang.System.load(System.java:1086)
[error]     at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
[error]     at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
[error]     at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:498)
[error]     at org.xerial.snappy.SnappyLoaderTest.loadSnappyByDiffentClassloadersInTheSameJVM(SnappyLoaderTest.java:106)
[error]     ...

I have not yet investigated the details, but the binary format looks illegal (see "architecture: UNKNOWN" in the following dump):

> $ objdump -f Contribution/snappy-java/src/main/resources/org/xerial/snappy/native/Linux/ppc64le/libsnappyjava.so
Contribution/snappy-java/src/main/resources/org/xerial/snappy/native/Linux/ppc64le/libsnappyjava.so:     file format elf64-little
**architecture: UNKNOWN!**, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x0000000000034520

**Comment by xerial** [comment]
Rebuilt ppc64le library. The previous version was not using cross compiler due to misconfiguration.

**Comment by xerial** [comment]
@odaira Two things:
- Please test ppc64le again.
- I'm struggling in building docker images for cross compilers of ppc64 (bigendian), ppc (32-bit). If you think supporting these CPU types is important, create PR(s) for adding these native libraries. 

Thanks in advance.

**Comment by odaira** [comment]
The new ppc64le/libsnappyjava.so works perfectly on ppc64le.  I am building native libraries for ppc and ppc64.  I have to ask a sysadmin to install some 32-bit packages, so it might take a few days to build a ppc binary.

**Comment by xerial** [comment]
Thanks for checking!  I've merged #169 to the master branch. Please create PRs based on the master.

**Comment by odaira** [comment]
Sorry, it turned out that the necessary 32-bit packages could not be installed easily.  I cannot build a 32-bit binary shortly.  It would take more than a month.  I believe few people are using 32-bit ppc Linux these days, so I think you can release a new version without it.

**Comment by xerial** [comment]
@odaira I got it. Thanks for your great contribution!

**Comment by xerial** [comment]
Released 1.1.4-M3 with ppc64 and ppc64le. Let me close this ticket.
