### ISSUE TITLE
Oracle and IBM licenses?

### ISSUE THREAD

**Issue by WhelanLabs** [xerial/snappy-java#171]
Hello,

In looking at the code, I noticed that there are some source files that identify themselves as having Oracle/Sun and IBM licensed content. However, from the files, I could not tell if the terms of the license allowed the files to be used in snappy-java. Some examples of these licensed files are:

[https://github.com/xerial/snappy-java/blob/1.1.2/lib/inc_ibm/jni_md.h](https://github.com/xerial/snappy-java/blob/1.1.2/lib/inc_ibm/jni_md.h)
[https://github.com/xerial/snappy-java/blob/1.1.2/lib/inc_linux/jni_md.h](https://github.com/xerial/snappy-java/blob/1.1.2/lib/inc_linux/jni_md.h)

Is there available information that identifies the license terms for these files?

John Whelan
Siemens Industry Sector
Siemens Product Lifecycle Management Software Inc.
5939 Rice Creek Parkway
Shoreview, MN  55126 United States 
www.siemens.com/plm

**Comment by xerial** [comment]
These files are a part of JDK, and are included for the convenience of the build. These files are not essential to build snappy-java. I'll remove these files.

Thanks.

**Comment by WhelanLabs** [comment]
Thanks!

**Comment by madrob** [comment]
@xerial I see that the files are still present in master branch. Do you still plan to remove them?
