### ISSUE TITLE
Update snappy-java to use snappy v1.1.7

### ISSUE THREAD

**Issue by paplorinc** [xerial/snappy-java#184]
See: https://github.com/google/snappy/blob/master/NEWS

**Comment by bokken** [comment]
+1

**Comment by xerial** [comment]
Start working on this in #185

**Comment by paplorinc** [comment]
Great, thank you!! :)

**Comment by xerial** [comment]
@paplorinc A snapshot version is available here https://oss.sonatype.org/content/repositories/snapshots/org/xerial/snappy/snappy-java/1.1.7-SNAPSHOT/ (except Windows support)

**Comment by paplorinc** [comment]
Thanks @xerial, will check it out shortly!

**Comment by xerial** [comment]
I'll release 1.1.7 after #186 is done.

**Comment by paplorinc** [comment]
I've benchmarked compression and decompression for `1.1.4` vs `1.1.7` and it seems it has the same performance as before.

**Comment by xerial** [comment]
@paplorinc Thanks. It seems the performance improvement is only for some specific CPU types (e.g., aach64, little-endian PowerPC, etc.) https://github.com/google/snappy/blob/master/NEWS

**Comment by paplorinc** [comment]
@xerial, thanks again for your hard work! :)
Is there an ETA for the `1.1.7` release?

**Comment by xerial** [comment]
Currently @odaira is working on supporting remaining OSs in #186. I don't want to push him, but the next release is not so far away. 

And also judging from Snappy's release notes, there is no fundamental changes other than release process (e.g., use of CMake) unless you are a big-endian architecture user. 

We are now revisiting how to build snappy-java based on this new cmake-based build script.

**Comment by paplorinc** [comment]
FYI: https://github.com/xerial/snappy-java/issues/186#issuecomment-348058604

**Comment by xerial** [comment]
I'm now working on Linux build so that we can use cmake generated headers properly inside docker image for cross building. Wait for a while.

**Comment by xerial** [comment]
Released snappy-java 1.1.7! 
https://github.com/xerial/snappy-java/blob/master/Milestone.md#snappy-java-117-2017-11-30

Many thanks @odaira-san for building native libs!

**Comment by paplorinc** [comment]
Good job @xerial and @odaira, thanks!
Btw, in the release notes you may want to append the `1.1.5` changelog, too:
https://github.com/google/snappy/releases/tag/1.1.5

**Comment by xerial** [comment]
@paplorinc Thanks. Added a note for 1.1.5 as well: https://github.com/xerial/snappy-java/commit/8686318c2c5b0b9c367933e78923a8085e11938f#diff-a923e3cd7fd24b0e20ef0518a5f9eff0
