### ISSUE TITLE
Build snappy-java 1.1.7 native libraries for s390x, AIX/Linux ppc64/ppc64le

### ISSUE THREAD

**Issue by xerial** [xerial/snappy-java#186]
@odaira 
Now that #185 is ready, could you try building snappy-java-1.1.7 for s390x, AIX/Linx ppc64/ppc64le?

**Comment by odaira** [comment]
OK, I will.

**Comment by odaira** [comment]
I have got this error.  Looks like there is no way to generate snappy-stubs-public.h.

```
$ env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-ppc64el make
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/odaira -Dos.arch=ppc64le
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/odaira -Dos.arch=ppc64le
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/odaira -Dos.arch=ppc64le
g++  -DHAVE_CONFIG_H -Ilib/inc_linux -I/usr/lib/jvm/java-8-openjdk-ppc64el/include -Ilib/inc_mac -O2 -fPIC -fvisibility=hidden -m64 -Ilib/include -I"/usr/lib/jvm/java-8-openjdk-ppc64el/include/linux" -Itarget/snappy-1.1.7 -Itarget/bitshuffle-0.3.2/src -c target/snappy-1.1.7/snappy-stubs-internal.cc -o target/snappy-1.1.7-Linux-ppc64le/snappy-stubs-internal.o
In file included from target/snappy-1.1.7/snappy-stubs-internal.cc:32:0:
target/snappy-1.1.7/snappy-stubs-internal.h:56:33: fatal error: snappy-stubs-public.h: No such file or directory
compilation terminated.
Makefile:118: recipe for target 'target/snappy-1.1.7-Linux-ppc64le/snappy-stubs-internal.o' failed
make: *** [target/snappy-1.1.7-Linux-ppc64le/snappy-stubs-internal.o] Error 1
```

**Comment by xerial** [comment]
@odaira OK. It seems we need to run cmake for these targets. So we need to add snappy-header task like:
https://github.com/xerial/snappy-java/blob/a450805eeb74aad618d1f981e59a641d40534964/Makefile#L170

**Comment by xerial** [comment]
I think adding snappy-header task in jni-header would work:
https://github.com/xerial/snappy-java/blob/a450805eeb74aad618d1f981e59a641d40534964/Makefile#L148

```
native: jni-header snappy-header $(NATIVE_DLL) 
```

**Comment by odaira** [comment]
Submitted #192.  It might take a few more days for the other platforms (Linux ppc64, AIX ppc, AIX ppc64, and Linux s390x) as I have to update and install somethings (e.g. cmake).

**Comment by xerial** [comment]
No problem. Thanks for your work!

**Comment by odaira** [comment]
Built on s390x, but the generated library failed in uncompress (FAILED_TO_UNCOMPRESS(5)).  Will investigate more....

**Comment by xerial** [comment]
The original Snappy itself might have an issue for big-endian architecture s390x: 
https://github.com/google/snappy/blob/master/NEWS

**Comment by odaira** [comment]
I think I figured out the cause of the problem on s390x.  cmake generates target/snappy-1.1.7-Linux-s390x/config.h, which defines SNAPPY_IS_BIG_ENDIAN on s390x.  However, the compiler refers to lib/include/config.h, which is an empty header file, before target/snappy-1.1.7-Linux-s390x/config.h.  As a result, SNAPPY_IS_BIG_ENDIAN is not defined properly on s390x.

I am wondering why the empty header lib/include/config.h exists, but a solution would be to add -DSNAPPY_IS_BIG_ENDIAN in Makefile, as with aarch64.  What do you think?

**Comment by xerial** [comment]
@odaira Good catch.
Actually I had a similar issue in Windows and enforced using a cmake generated header file here:
https://github.com/xerial/snappy-java/blob/master/Makefile#L109

Snappy's cmake generates snpapy-stubs-public.h, which hard codes `SNAPPY_IS_BIG_ENDIAN=1 or 0`, so we probably cannot dynamically switch the behavior. But it's worth a try.

Another approach is using snappy's cmake generated Makefile to build snappy binaries, but we need to tweak the current Makefile for doing so.

**Comment by odaira** [comment]
As far as I read the code, snpapy-stubs-public.h.in and generated snpapy-stubs-public.h do not refer to or hard-code SNAPPY_IS_BIG_ENDIAN, do they?

**Comment by xerial** [comment]
What I saw was `HAVE_SYS_UIO_H`, so SNAPPY_IS_BIG_ENDIAN should be OK to use.  
```
#if !0  // !HAVE_SYS_UIO_H
// Windows does not have an iovec type, yet the concept is universally useful.
// It is simple to define it ourselves, so we put it inside our own namespace.
struct iovec {
	void* iov_base;
	size_t iov_len;
};
#endif  // !HAVE_SYS_UIO_H```

**Comment by odaira** [comment]
OK, so back to my original question, can you tell me why lib/include/config.h exists?

**Comment by xerial** [comment]
Previous versions of Snappy needee configure step, but now that it uses cmake and stub header file, we no longer need it.

**Comment by odaira** [comment]
I think I am done.

**Comment by xerial** [comment]
Thanks! Let me close this ticket.
