### ISSUE TITLE
can we create pom.xml to build snappy-java

### ISSUE THREAD

**Issue by anuscool** [xerial/snappy-java#200]
can we use pom.xml to build snappy-java,instead of sbt

**Comment by xerial** [comment]
@anuscool For what? Personally I don't want to go back mvn only build configuration. Using gradle etc. can be an option.

**Comment by anuscool** [comment]
can you tell me,pom support is avilable for snappy java in maven repository/central

**Comment by xerial** [comment]
pom.xml is already available in Maven central.

**Comment by anuscool** [comment]
can you send me the path where pom.xml is avilable.
why this pom.xml is not present in source code repository of xerial snappy java?
we can use pom.xml to build snappy-java?

**Comment by xerial** [comment]
@anuscool How to build snappy-java is already described in README.md. You don't need to use maven. 

And you can find pom.xml in Maven central
http://search.maven.org/#artifactdetails%7Corg.xerial.snappy%7Csnappy-java%7C1.1.7.1%7C
