### ISSUE TITLE
is there any performance improvement scope of snappy java

### ISSUE THREAD

**Issue by anuscool** [xerial/snappy-java#201]
is there any software tool or library to increase performance of snappy java and how we can test it.

**Comment by xerial** [comment]
See https://github.com/xerial/snappy-java#performance

**Comment by anuscool** [comment]
at below link jatex test report is given
http://ning.github.io/jvm-compressor-benchmark/results/canterbury-uncompress-2011-07-28/index.html

if i have to run this on my snappy-java folder,how i will test it on linux64.

**Comment by xerial** [comment]
Use this tool: https://github.com/ning/jvm-compressor-benchmark/wiki
