### ISSUE TITLE
64-bit optimized code path for arm64 comes with performance improvement

### ISSUE THREAD

**Issue by anuscool** [xerial/snappy-java#202]
snappy 1.1.7 comes with performance optimization for 64-bit optimized path for arm64...is this true?

**Comment by xerial** [comment]
Yes. A native library bundled for arm64 has this optimization.

**Comment by anuscool** [comment]
what will be the  Test plan regarding performance improvement scope, measurement and reference comparision for this......

**Comment by xerial** [comment]
So far I have no specific plan for benchmarking, especially because I'm not using aarch64 CPUs. I'd appreciate contributions (e.g., taking a benchmark with aarch64) in this regard.
