### ISSUE TITLE
java not found issue during cross compiling for armv7,using command make linux-armv7

### ISSUE THREAD

**Issue by anuscool** [xerial/snappy-java#203]
./docker/dockcross-armv7 -a --rm bash -c 'make clean-native native CROSS_PREFIX=arm-linux-gnueabihf- OS_NAME=Linux OS_ARCH=armv7'
/bin/sh: 1: /bin/java: not found
/bin/sh: 1: /bin/java: not found
/bin/sh: 1: /bin/java: not found
find: `/usr/lib/jvm/java-8-openjdk-amd64': No such file or directory

i am getting this error when i am cross compiling it,i have already set JAVA_HOME path,but only during cross compiling i am getting this error.

**Comment by xerial** [comment]
@anuscool 
I'm not sure what you are trying to do, but this error is happening in this line:
```
Makefile.common:jni_md := $(shell find -L "$(JAVA_HOME)" -name jni_md.h | head -1)
```

And your error message indicates that there is no installed Java in your JAVA_HOME.
