### ISSUE TITLE
query regarding maven for snappy-java

### ISSUE THREAD

**Issue by anuscool** [xerial/snappy-java#204]
snappy-java-1.0.5.4 version contain pom.xml but after that pom.xml is removed and sbt is added.
in this pom i am not getting any source code of google snappy.

i want to confirm can we build xerial-snappy with pom file,we have to donwload the google snappy in our pom file.

pom file support for xerial snappy is present on maven central.

**Comment by xerial** [comment]
@anuscool For building snappy-java, you don't need pom.xml. See https://github.com/xerial/snappy-java#for-developers first. 

pom.xml will be generated upon publishing snappy-java to Maven central.
