### ISSUE TITLE
[DOCS] Java doc about the snappy output data format needs to be optimized

### ISSUE THREAD

**Issue by xuchuanyin** [xerial/snappy-java#205]
I need to produce data file with snappy compressed using Snappy C library and consume it using snappy-java. 

I followed the java docs in `SnappyOutputStream` and try to write the data file in C language just like the snappy-java's SnappyOutputStream do but end with failure.
Finally I find out that, besides writing the snappy magic header (8 bytes) described in ``
```
new byte[] {-126, 'S', 'N', 'A', 'P', 'P', 'Y', 0}
```
We also need to write another 8 bytes: 2 integers each with 4 bytes representing `version` and `compatible version`. The version should at least be 1.
---- I think the above information should be added to the `SnappyOutputStream`.

**Comment by xerial** [comment]
done in #206
