### ISSUE TITLE
core snappy

### ISSUE THREAD

**Issue by youyong205** [xerial/snappy-java#207]
Snappy Java » 1.1.4-M3

============================================================

this is the core dump binary stack
----------------- 35825 -----------------
0x000000302ac325e5	__GI_raise + 0x35

============================================================
gdb core file show
(gdb) where
#0  0x000000302ac325e5 in ?? ()
#1  0x000000302ac33dc5 in ?? ()
#2  0x00002b225d748408 in ?? ()

============================================================
thread id is 35825 ,check jstack 

Thread 35825: (state = IN_NATIVE)
- org.xerial.snappy.SnappyNative.rawCompress(java.lang.Object, int, int, java.lang.Object, int) @bci=0 (Compiled frame; information may be imprecise)
- org.xerial.snappy.Snappy.rawCompress(java.lang.Object, int, int, byte[], int) @bci=27, line=446 (Compiled frame)
- org.xerial.snappy.Snappy.compress(byte[], int, int, byte[], int) @bci=6, line=119 (Compiled frame)
- org.xerial.snappy.SnappyOutputStream.compressInput() @bci=42, line=376 (Compiled frame)
- org.xerial.snappy.SnappyOutputStream.flush() @bci=18, line=334 (Compiled frame)

============================================================
System info
Linux version 2.6.32-431.20.3  
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

============================================================

This core appeared once in a few weeks，Do anyone have the same situation？

**Comment by youyong205** [comment]
thanks. we will update in this week. 

========================================

I'd like to know if I've ever met such a situation before.
I have check the version of 1.1.7.1 and 1.1.4 md5, They have a little difference.

MD5 (1.1.4.so) = 2b906715cc3a1f20be195902e12f5481
MD5 (1.1.7.so) = 49565bbde85c6e1f5600914784198729

**Comment by xerial** [comment]
I haven't seen this type of error in SnappyOutputStream. If you read corrupted data in SnappyInputStream such an error could happen.
