### ISSUE TITLE
New Feature RandomAccess in streams

### ISSUE THREAD

**Issue by publicocean0** [xerial/snappy-java#208]
It would be very usefull random access (position) for compressed stream.

**Comment by xerial** [comment]
To support random access, somebody needs to manage offsets to compressed chunks. I guess this is out of scope of snappy-java in a sense providing snappy compressor, originally implemented in C++, to Java world.

**Comment by publicocean0** [comment]
Ok i m implementing on my own. Please i need just a info. 
 Snappy.compress(byte[40])
 Snappy.compress(byte[60])


then i read
 Snappy.uncompress(byte[50])
 Snappy.compress(byte[50])  
 

does it work? pratically the compression is invariant or it keeps a state about compression length so i need to uncompress 
 Snappy.uncompress(byte[40])
 Snappy.compress(byte[60])

?

**Comment by xerial** [comment]
I'm not sure this is helpful or not, but for checking uncompressed data length, you can use:
https://oss.sonatype.org/service/local/repositories/releases/archive/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1-javadoc.jar/!/org/xerial/snappy/Snappy.html#uncompressedLength-byte:A-

**Comment by publicocean0** [comment]
Yes for making it seekable ,might be not difficult. The difficult if I want also to add write method. Space compressed might be depending by content , so if write 10 bytes , and then I replace 10 bytes i thing space could be different
