### ISSUE TITLE
doubleArray, simpleUsage, string,... tests in snappy-java 1.1.7 failing due to IOException on AARCH64 board

### ISSUE THREAD

**Issue by chvsree2007** [xerial/snappy-java#209]
Used ./sbt to run the test cases after compiling snappy-java 1.1.7 code. Found below error on AARCH64 board. Issue is in "DecompressALLTags()" in "target/snappy-1.1.7/snappy.cc" file. Test cases are failing when both "decompressor->eof()" and "writer->checklength()" are returning "0".
No IOExceptions were found on x86 (Ubuntu VM), all test cases passed. Is there architecture specific code I need to change for aarch64? Can someone help me on this?
./sbt
sbt:snappy-java> ~test
......
[error] Test org.xerial.snappy.SnappyTest.doubleArray failed: java.io.IOException: FAILED_TO_UNCOMPRESS(5), took 0.009 sec
[error]     at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
[error]     at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
[error]     at org.xerial.snappy.Snappy.uncompressDoubleArray(Snappy.java:597)
[error]     at org.xerial.snappy.SnappyTest.doubleArray(SnappyTest.java:261)
[error]     ...
[info] Test org.xerial.snappy.SnappyTest.simpleUsage started
[error] Test org.xerial.snappy.SnappyTest.simpleUsage failed: java.io.IOException: FAILED_TO_UNCOMPRESS(5), took 0.006 sec
[error]     at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
[error]     at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
[error]     at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:474)
[error]     at org.xerial.snappy.Snappy.uncompress(Snappy.java:513)
[error]     at org.xerial.snappy.Snappy.uncompress(Snappy.java:488)
[error]     at org.xerial.snappy.SnappyTest.simpleUsage(SnappyTest.java:240)
[error]     ...
[info] Test org.xerial.snappy.SnappyTest.floatArray started
[info] Test org.xerial.snappy.SnappyTest.string started
[error] Test org.xerial.snappy.SnappyTest.string failed: java.io.IOException: FAILED_TO_UNCOMPRESS(5), took 0.002 sec
[error]     at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
[error]     at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
[error]     at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:474)
[error]     at org.xerial.snappy.Snappy.uncompress(Snappy.java:513)
[error]     at org.xerial.snappy.Snappy.uncompress(Snappy.java:488)
[error]     at org.xerial.snappy.Snappy.uncompressString(Snappy.java:887)
[error]     at org.xerial.snappy.Snappy.uncompressString(Snappy.java:807)
[error]     at org.xerial.snappy.SnappyTest.string(SnappyTest.java:311)
[error]     ...

**Comment by ubnt-yhlee** [comment]
@xerial I think this is fixed by #213 and included in 1.1.7.2.

**Comment by xerial** [comment]
@ubnt-yhlee 
Thanks! I'll close this ticket.
