### ISSUE TITLE
Snappy 1.1.7.1 and 1.1.7.2 does not work on ppc64le because of glibc 2.22 dependency

### ISSUE THREAD

**Issue by nbathra** [xerial/snappy-java#220]
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-47312095-8ab9-48a7-885f-cea7c7614fd6-libsnappyjava.so: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /tmp/snappy-1.1.7-47312095-8ab9-48a7-885f-cea7c7614fd6-libsnappyjava.so)

Any specific reason why this dependecy is introduced in the first place?
Secondly, I couldn't find the GlibC 2.22 for ppc64le for RHEL74 and RHEL75 , in that case can snappy be compiled with GLIB2.17 itself ?

**Comment by jamesbroadhead** [comment]
@xerial we have run into this as well. 
We need to support RHEL7 on PPC - and [RHEL7's glibc version is  glibc 2.17](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.0_release_notes/sect-red_hat_enterprise_linux-7.0_release_notes-compiler_and_tools-glibc)

This is not a problem with snappy-java's builds on x86 - these work fine on RHEL7 - so they must be built against an older glibc than that used on ppc64le.  

Could you please reconsider & do a build and release which is compatible with RHEL on ppc64le? 

We would really prefer not to maintain a forked build - but could provide a build of libsnappyjava.so built on RHEL7/ppc64le if you would consider releasing it.

**Comment by xerial** [comment]
@jamesbroadhead Binaries for Linux/ppc64le can be built by using a cross compiler provided by https://github.com/dockcross/dockcross/tree/master/linux-ppc64le

If we can create a docker image that contains a cross compiler for ppc64le and uses an older version of glibc (e.g., REHL7), we can build a binary for your environment by simply changing this line:
https://github.com/xerial/snappy-java/blob/master/Makefile#L204

**Comment by xerial** [comment]
It should be fixed in snappy-java 1.1.7.4

**Comment by nbathra** [comment]
Thanks @xerial .
