### ISSUE TITLE
illegal reflective access

### ISSUE THREAD

**Issue by gordonritter** [xerial/snappy-java#224]
I'm using the very latest version of snappy-java and java 11. Any attempt to write a file using SnappyFramedOutputStream results in the following warnings, which i believe are all due to the "sun direct buffer" mechanism in SnappyFramed. Specifically, the latter references sun.nio.ch.DirectBuffer and sun.misc.Cleaner, and I think the creators of java intend to remove all access to sun.* packages at some point. 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xerial.snappy.SnappyFramed (file:/Users/gordonritter/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.2/snappy-java-1.1.7.2.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.xerial.snappy.SnappyFramed
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by xerial** [comment]
Fixed by #228
