### ISSUE TITLE
SnappyFramed streams to pool byte[] and direct ByteBuffer instances

### ISSUE THREAD

**Issue by bokken** [xerial/snappy-java#233]
There would be performance benefit to caching/reusing both byte[] and direct ByteBuffer instances as part of the SnappyFramed InputStream and OutputStream implementations.

It appears that the SnappyOutputStream class uses the [CachedBufferAllocator](https://github.com/xerial/snappy-java/blob/master/src/main/java/org/xerial/snappy/buffer/CachedBufferAllocator.java) to cache/reuse byte[] instances.

I am personally finding the `BufferAllocatorFactory` and `BufferAllocator` api a bit confusing. Both specify a size and it seems there is nothing to require those sizes align with each other.

I would like to propose a new api which just defines an interface to allocate and return objects of various sizes to. It would be up to the implementation to handle the different sizes of objects being requested. Something like:

```
public interface BufferPool {
    
    /**
     * Returns a {@code byte[]} of <i>size</i> or greater length.
     * @param size The minimum size array required. Must be {@code >= 0}.
     * @return A {@code byte[]} with length of at least <i>size</i>.
     * @see #releaseArray(byte[])
     */
    public byte[] allocateArray(int size);

    /**
     * Returns instance to pool for potential future reuse.
     * <p>
     * Must not be returned more than 1 time. Must not be used by caller after return.
     * </p>
     * @param buffer Instance to return to pool. Must not be {@code null}.
     * Must not be returned more than 1 time. Must not be used by caller after return.
     */
    public void releaseArray(byte[] buffer);

    /**
     * Returns a {@link ByteBuffer#allocateDirect(int) direct ByteBuffer} of <i>size</i> or
     * greater {@link ByteBuffer#capacity() capacity}.
     * @param size The minimum size buffer required. Must be {@code >= 0}.
     * @return A {@code ByteBuffer} of <i>size</i> or greater {@link ByteBuffer#capacity() capacity}.
     * @see #releaseDirect(ByteBuffer)
     * @see ByteBuffer#allocateDirect(int)
     */
    public ByteBuffer allocateDirect(int size);

    /**
     * Returns instance to pool for potential future reuse.
     * <p>
     * Must not be returned more than 1 time. Must not be used by caller after return.
     * </p>
     * @param buffer Instance to return to pool. Must not be {@code null}.
     * Must not be returned more than 1 time. Must not be used by caller after return.
     */
    public void releaseDirect(ByteBuffer buffer);
}
```

It seems that 'BufferAllocator' and 'BufferAllocatorFactory' could be deprecated/replaced with this type of api (perhaps adding a class to manage a default instance to use).

Or would it be preferred to extend/update the existing `BufferAllocator` interface? Adding methods to the interface would be non-passive and break any consumer who provided a custom implementation.

**Comment by bokken** [comment]
@xerial, any thoughts on this?

**Comment by xerial** [comment]
@bokken It took me for a while to remind how this interface was introduced. The proposed change to BufferAllocator looks ok. No need to follow the existing one as the current BufferAllocator is not public facing API.

**Comment by bokken** [comment]
@xerial, does that mean you would like me to merge the new package/classes/methods developed in https://github.com/xerial/snappy-java/pull/234 into the existing BufferAllocator?
Or would you prefer to deprecate the existing buffer.BufferAllocator and move to pool.BufferPool even for existing SnappyOutputStream.

**Comment by xerial** [comment]
I don't want to change the behavior of SnappyOutputStream for now. Applying this approach only for SnappyFramed streams is preferred. #234 is basically LGTM.

**Comment by bokken** [comment]
@xerial Do you have an ETA on merging https://github.com/xerial/snappy-java/pull/234 and doing a release?

**Comment by xerial** [comment]
It's been released. let me close this
