### ISSUE TITLE
Can not built on newer JDKs: no "javah" tool

### ISSUE THREAD

**Issue by blacklion** [xerial/snappy-java#242]
I'm trying to build 1.1.7.3 release (tag) with OpenJDK 12 and get:

```
"$JAVA_HOME/bin/javah" -force -classpath target/jni-classes -o src/main/java/org/xerial/snappy/SnappyNative.h org.xerial.snappy.SnappyNative
/bin/sh: /usr/local/openjdk12/bin/javah: not found
gmake: *** [Makefile:96: src/main/java/org/xerial/snappy/SnappyNative.h] Error 127
```

`javah` was removed at Java10 2 years ago…

**Comment by xerial** [comment]
#238 should fix this issue. Backporting might be necessary, but I prefer releasing a next version (e.g., 1.1.7.4)

**Comment by xerial** [comment]
Let me close the issue as a fix is already merged.
