### ISSUE TITLE
1.1.7.4 jar in maven central missing pool package

### ISSUE THREAD

**Issue by bokken** [xerial/snappy-java#245]
The 1.1.7.4 [jar deployed to maven central](https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.4/snappy-java-1.1.7.4.jar) is missing the org.xerial.snappy.pool package. This means the SnappyFramed classes do not work.

Interestingly, the [sources jar](https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.4/snappy-java-1.1.7.4-sources.jar) does have the package.

**Comment by JimNero009** [comment]
My original issue that I've consolidated to this:

We have a library that depends on yours. We were very happily using version 1.1.7.3 and then tried to update to version 1.1.7.4. When we do, we find some of the methods break:

java.lang.NoClassDefFoundError: org/xerial/snappy/pool/DefaultPoolFactory

There are two such instances, which are using the SnappyFramedOutputStream and SnappyFramedInputStream constructors with a single argument passed, which are a new ByteArrayOutputStream and a ByteArrayInputStream.

Is this an unintended consequence of the release?

**Comment by xerial** [comment]
I've found osgi configuration didn't include org.xerial.snappy.pool package and it caused missing class files. I'll fix it.

**Comment by xerial** [comment]
Just released 1.1.7.5 with a fix for this.

**Comment by bokken** [comment]
1.1.7.5 has definitely fixed it.

**Comment by xerial** [comment]
@bokken Thanks for the confirmation.
