### ISSUE TITLE
Version 1.1.7.4: NoClassDefFoundError: org/xerial/snappy/pool/DefaultPoolFactory

### ISSUE THREAD

**Issue by JimNero009** [xerial/snappy-java#246]
Hello!
We have a library that depends on yours. We were very happily using version 1.1.7.3 and then tried to update to version 1.1.7.4. When we do, we find some of the methods break: 

`java.lang.NoClassDefFoundError: org/xerial/snappy/pool/DefaultPoolFactory`

There are two such instances, which are using the `SnappyFramedOutputStream` and `SnappyFramedInputStream` constructors with a single argument passed, which are a new `ByteArrayOutputStream` and a `ByteArrayInputStream`.

Is this an unintended consequence of the release?

**Comment by bokken** [comment]
I noticed the same thing this morning: https://github.com/xerial/snappy-java/issues/245

**Comment by JimNero009** [comment]
Ah, brilliant -- let's consolidate on that issue.

**Comment by JimNero009** [comment]
Closing in favour of duplicate #245
