### ISSUE TITLE
java.lang.NoSuchMethodError when calling compress(ByteBuffer, ByteBuffer)

### ISSUE THREAD

**Issue by disturbedsaint** [xerial/snappy-java#251]
Starting in version `1.1.7.4` of snappy, when I attempt to call compress(ByteBuffer, ByteBuffer), I see the following exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
        at org.xerial.snappy.Snappy.compress(Snappy.java:152)
        at SnappyRepro.App.main(App.java:15)
```

This is almost certainly the issue that is described in [this stackoverflow post](https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip). I suspect that between version `1.1.7.3` and `1.1.7.4` of snappy, the JDK used to compile the official version of the library was updated.

I've uploaded https://github.com/disturbedsaint/SnappyRepro with reproduction instructions.

**Comment by disturbedsaint** [comment]
I just noticed https://github.com/xerial/snappy-java/issues/247 - and have confirmed that `1.1.7.5` also works for me. But the issues appears to be back in `1.1.7.6`.

**Comment by xerial** [comment]
Released 1.1.7.7 recompiled with JDK8. I still need a more reliable way to compile snappy-java with jdk11 to avoid this type of incompatibility issue.

**Comment by bokken** [comment]
I am not sure how to do it with gradle, but jdk 9 introduced the "release" argument for javac. [Here](https://docs.oracle.com/en/java/javase/11/tools/javac.html#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9) is the jdk 11 doc.

> Compiles against the public, supported and documented API for a specific VM version. Supported release targets are 6, 7, 8, 9, 10, and 11.

**Comment by xerial** [comment]
Yeah. I've tried `--release 8` option, but it caused another issue because this option totally hides sun.misc.Unsafe APIs, which are used inside the pure-scala implementation.

**Comment by bokken** [comment]
Ah yes. That is noted:

> When using --release for a version of the Java Platform that supports modules, you can’t use --add-modules to access internal JDK modules, nor can you use --add-exports to access internal JDK APIs in the modules.

**Comment by xerial** [comment]
`--add-exports` is worth trying. Thanks

**Comment by xerial** [comment]
ah. The doc says it can't be used with release option. Hm. We need to seek an option to use only JDK8/11 compatible ByteBuffer methods.

**Comment by xerial** [comment]
Let me close this issue as 1.1.7.7 should solve this issue. The future improvement ideas are ticketed in #252 #253

**Comment by ijuma** [comment]
@xerial In Apache Kafka, we use `--release 8` and it works fine. We had to upgrade to a recent Gradle version that includes a recent enough version of Zinc for it to work.

**Comment by xerial** [comment]
@ijuma Yes. I've tried `--release 8` but snappy-java uses sun.misc.Unsafe and this option caused compilation errors.

**Comment by ijuma** [comment]
Kafka does too: https://github.com/apache/kafka/blob/be58580e14be93618f11e609389ff6bb16317702/clients/src/main/java/org/apache/kafka/common/utils/ByteBufferUnmapper.java

**Comment by xerial** [comment]
I see. So instead of importing `sun.misc.Unsafe`, we can use reflection to avoid direct reference to sun.misc.Unsafe

**Comment by xerial** [comment]
Now that pure-java Snappy code has been removed, we can enable `--release 8` option. #390 This issue should be fixed in the upcoming version.
