### ISSUE TITLE
How to add additional metdata to Maven Repository information

### ISSUE THREAD

**Issue by oleg-cherednik** [xerial/snappy-java#259]
Hi.

Sorry for asking here as an issue. I have question to you. How did you add following information to you artefact in Maven Rpository:

- A custom icon
- Categories: Custom Libraries
- Tags: compression

Thank you in advance. I will be appreciate for this info.

**Comment by xerial** [comment]
There is no explicit metadata in this repository. Probably search.maven.org is automatically labaling maven artifacts
