### ISSUE TITLE
[FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64

### ISSUE THREAD

**Issue by Guzi219** [xerial/snappy-java#276]
Hi, I'm using the new macbook(with m1 chip inside),
I got the error:
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64, org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:342)

JVM version: 
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+1021-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+1021-CA (build 11.0.9.1+1-LTS, mixed mode)

any plan to support The new  mac m1?
thanks a lot.

**Comment by xerial** [comment]
Use snappy-java 1.1.8.2 or later. It's already supported

**Comment by xerial** [comment]
If it still doesn't work, reopen the issue by mentioning the version you used.
