### ISSUE TITLE
Migrating to travis-ci.com

### ISSUE THREAD

**Issue by srajmane** [xerial/snappy-java#285]
From June 15th, 2021, the building on travis-ci.org is ceased.
Do we have any plans to migrate the repository to travis-ci.com? This is important for architectures like s390x which have CI support through Travis only.

**Comment by xerial** [comment]
I haven't considered using travis-ci.com. 

If it's free or we can have a budget for using it, it would be worth migrating it.

**Comment by srajmane** [comment]
OSS is free on travis.com (Ref: https://blog.travis-ci.com/oss-announcement)
They do have credits given for OSS, and if more is needed issue can be raised.

**Comment by srajmane** [comment]
@xerial 
Any update on this? I have observed GA is not active for a long time.
Any future plans for CI?

**Comment by xerial** [comment]
It’s simply because we have no recent changes. If there is no commit, GA will not trigger any build.

**Comment by srajmane** [comment]
> I haven't considered using travis-ci.com.
> 
> If it's free or we can have a budget for using it, it would be worth migrating it.

@xerial s390x native builds are not supported on GA builds yet. So can we plan for Travis migration to travis-ci.com?

**Comment by xerial** [comment]
The migration has been completed. If you see any issue, please create a PR as supporting s390x is not my primary interest.
