### ISSUE TITLE
Unable to start snappy-java as OSGi bundle on Apple Silicon (M1 Pro)

### ISSUE THREAD

**Issue by zh-muxa** [xerial/snappy-java#302]
Installing snappy-java (1.1.8.4) as an OSGi bundle on Apache Karaf (4.3.5) and then running the bundle leads to an error:

![Screenshot 2022-01-19 at 17 08 06](https://user-images.githubusercontent.com/56256475/150149558-9beb0b13-2a3c-4c75-98dd-9e54105f7f98.png)

**Comment by jrnorth** [comment]
@xerial Any idea when the next version will be released? I could use this fix.

**Comment by xerial** [comment]
Released 1.1.9.0 with this fix.
