### ISSUE TITLE
Full copyright notice from hadoop-common not included in NOTICE

### ISSUE THREAD

**Issue by tazle** [xerial/snappy-java#308]
I would expect snappy-java's NOTICE file to include https://github.com/apache/hadoop/blob/trunk/NOTICE.txt verbatim as per section 4d of the Apache License 2.0.

This certainly seems to be what hadoop are doing themselves for their various dependencies in https://github.com/apache/hadoop/blob/trunk/NOTICE-binary

**Comment by xerial** [comment]
Addressed in #492
