### ISSUE TITLE
Upgrade to snappy 1.1.9

### ISSUE THREAD

**Issue by lehnerj** [xerial/snappy-java#310]
Snappy 1.1.9 was released on 2021-05-05 (a year ago).
Would you be so kind and let us know when you plan to update snappy-java?

**Comment by abhisheksurve45** [comment]
+1

**Comment by anton-vinogradov** [comment]
+1

**Comment by xerial** [comment]
Released https://github.com/xerial/snappy-java/releases/tag/v1.1.9.0
