### ISSUE TITLE
org.xerial.snappy.SnappyError: [UNSUPPORTED_PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field

### ISSUE THREAD

**Issue by chiranth** [xerial/snappy-java#322]
Hello Guys,

We recently upgraded to jdk 17 with Redhat as base image and ever since we started getting the below error
org.xerial.snappy.SnappyError: [UNSUPPORTED_PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field

snappy version : 1.1.8.4(works with jdk11 Redhat base image but not when we upgrade to jdk17 Redhat base image)

If i revert to jdk11 Redhat docker base image, the issue goes away. I was refering to https://github.com/xerial/snappy-java/issues/289 which is basically same but alpine based docker image is being used over there and the solution is wrt to a alpine package, What do i have to do in Redhat base docker mage for jdk 17? Appreciate any help on this

**Comment by chiranth** [comment]
We were able to workaround the problem by adding the runtime java env --add-opens=java.base/java.nio=ALL-UNNAMED which resolved the problem
Ref: https://stackoverflow.com/questions/69728301/unable-to-make-field-long-java-nio-buffer-address-accessible-module-java-base-d
https://blogs.oracle.com/javamagazine/post/its-time-to-move-your-applications-to-java-17-heres-why-and-heres-how

But the above seems like a last resort workaround as per the above link and probably might need the fix in snappy?

**Comment by ebuildy** [comment]
We run a similar issue too, using Alpine as base Docker image. The solution was to install a native lib and tell to Spark to use it.

I wrote a small post : https://thomasdecaux.medium.com/use-snappy-compression-native-when-running-spark-on-alpine-5fee0ce28ed7 

1) ``apk add java-snappy-native``
2) ``
spark.executor.extraJavaOptions: -Dorg.xerial.snappy.use.systemlib=true -Dorg.xerial.snappy.lib.path=/usr/lib/libsnappyjava.so``

**Comment by caodangtinh** [comment]
In my case, I'm using Apache Parquet with Hadoop client library. I faced same issue with snappy-java library.
The fix solution is

1. Add native library of java-snappy: `sudo apk updateapk --no-cache update && sudo apk add java-snappy-native`
2. Add JVM arguments when starting application: `java -jar -Dorg.xerial.snappy.use.systemlib=true -Dorg.xerial.snappy.lib.path=/usr/lib/libsnappyjava.so app_name.jar`

**Comment by caodangtinh** [comment]
If you are using alpine linux (also with docker), let try to adding `gcompat` package.

`apk add --no-cache gcompat`

In my case worked with jdk17 as well

**Comment by a364176773** [comment]
> We run a similar issue too, using Alpine as base Docker image. The solution was to install a native lib and tell to Spark to use it.
> 
> I wrote a small post : https://thomasdecaux.medium.com/use-snappy-compression-native-when-running-spark-on-alpine-5fee0ce28ed7
> 
> 1. `apk add java-snappy-native`
> 2. ` spark.executor.extraJavaOptions: -Dorg.xerial.snappy.use.systemlib=true -Dorg.xerial.snappy.lib.path=/usr/lib/libsnappyjava.so`

I found that after the java-snappy-native installation finished, my jdk became jdk8 instead of jdk17

**Comment by xerial** [comment]
Released https://github.com/xerial/snappy-java/releases/tag/v1.1.9.0, which dropped pure-java support.
