### ISSUE TITLE
Snappy is built with debug assertions enabled

### ISSUE THREAD

**Issue by zcronix** [xerial/snappy-java#342]
The source files pulled in from google/snappy make use of assert() for debugging, which are expected to be disabled in release builds when following their cmake build process by the presence of -DNDEBUG in the CXXFLAGS. 

This flag is not specified for building those files as part of snappy-java. As a result, we discovered (due to a bug in our software) that it is possible to trigger failures of those assertions when using snappy-java, which terminates the process instead of propagating an exception back to Java code.

**Comment by xerial** [comment]
Good catch. Testing it at https://github.com/xerial/snappy-java/pull/386
