### ISSUE TITLE
Use Unsafe to obtain location of direct Buffer address field

### ISSUE THREAD

**Issue by YouBin-Choi** [xerial/snappy-java#348]
in java 16, Strongly Encapsulate JDK Internals by Default (https://openjdk.org/jeps/396).

And, UnsafeUtil class still in use reflection access (https://github.com/xerial/snappy-java/blob/master/src/main/java/org/xerial/snappy/pure/UnsafeUtil.java#L44).

so, when use jdk 16+, get error message 
`[UNSUPPORTED_PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field`.

Base project aircompressor is already fix this issue (https://github.com/airlift/aircompressor/pull/128)

please fix to usefully for jdk16+

**Comment by xerial** [comment]
I've dropped the pure-java support in https://github.com/xerial/snappy-java/releases/tag/v1.1.9.0 I think this is no longer an issue
