### ISSUE TITLE
Trigger native lib build with a PR comment

### ISSUE THREAD

**Issue by xerial** [xerial/snappy-java#437]
Building native libraries is running at GitHub Actions because I no longer have any local machine using Intel.
Currently, I'm manually triggering native lib build process at https://github.com/xerial/snappy-java/actions/workflows/build-native.yml

It would be convenient if we can trigger such a build if a maintainer comments to a PR (e.g., build native)

**Comment by imsudiproy** [comment]
@xerial  If I not wrong. We want to trigger a build when the maintainer comments on a PR with a specific keyword like 'build native'

**Comment by imsudiproy** [comment]
You can assign this to me. I'll work on this issue

**Comment by xerial** [comment]
@imsudiproy Thanks!

A trigger condition can be simpler like this:
- Trigger the build if there is a change in some of the following files:
  - src/main/resources/org/xerial/snappy/VERSION file
  - Makefile
  - Makefile.common
  - **/*.h
  - **/*.cpp

Trigging via PR comment might be unnecessary if the above condition works

**Comment by imsudiproy** [comment]
Hi @xerial , created a PR for this https://github.com/xerial/snappy-java/pull/444 let me know if any changes required. Thanks

**Comment by xerial** [comment]
Thanks. I've tested various approaches, and adopted 
- For PRs: Only testing native library build pass
- After PR merge, creating (or updating) a new PR with updated native libraries

**Comment by xerial** [comment]
Example PR created by this change https://github.com/xerial/snappy-java/pull/445
