### ISSUE TITLE
s390x native library fails to load

### ISSUE THREAD

**Issue by pawelszkiler** [xerial/snappy-java#464]
It looks like, after https://github.com/xerial/snappy-java/pull/416, the native library fails to load on a few s390x machines. 

Failing OSes include (ones that I was able to check):
- RHEL 7, RHEL 8
- Ubuntu 16, Ubuntu 18, Ubuntu 20
- SLES15 SP3, SLES 15 SP4

The error message says:
`libsnappyjava.so: /lib64/libc.so.6: version 'GLIBC_2.32' not found (required by libsnappyjava.so).`

Previously used version, 1.1.9.1, was working properly and already included s390x native library:

`
snappy-java-1.1.9.1\org\xerial\snappy\native\Linux
├───aarch64
├───android-arm
├───arm
├───armv6
├───armv7
├───ppc
├───ppc64
├───ppc64le
├───s390x
├───x86
└───x86_64
`

so I'm thinking: is the change done in https://github.com/xerial/snappy-java/pull/416 really needed?

Thanks for looking into it.

**Comment by pawelszkiler** [comment]
One important addition: 1.1.9.1, which is currently used, is prone to three high-score vulnerabilities: 
https://github.com/advisories/GHSA-pqr6-cmr2-h8hf
https://github.com/advisories/GHSA-fjpj-2g6w-x25r
https://github.com/advisories/GHSA-qcwq-55hx-v3vh
which is the reason I've tried updating to a version that has those vulnerabilities resolved.

**Comment by xerial** [comment]
Without #416, I can't build any native libraries for s390x by myself. 

I can accept a PR for adding native libraries built with an older version of Linux like RHEL7. Run `make native` and create a PR that contains an updated native library for s390x.

**Comment by xerial** [comment]
The latest version might have fixed this issue.

**Comment by kun-lu20** [comment]
PR #481 would fix this issue on s390x. 

@xerial Could you please take a look? Thank you very much!

**Comment by xerial** [comment]
Thanks all for the contributions! I just released snappy-java 1.1.10.3 with this fix

**Comment by kun-lu20** [comment]
Thanks @xerial ! I just tested the newly released `libsnappyjava.so` for s390x, it worked fine on Linux distributions mentioned in this issue as well as newer ones.

**Comment by pawelszkiler** [comment]
@xerial @kun-lu20 I also checked on RHEL 7 and Ubuntu 20 - works as expected. Thanks a lot!

**Comment by vineshcpaul** [comment]
@xerial , could you please help fix this issue on ppc64le as well? Opened #512
