### ISSUE TITLE
[Question] Why are we using -O2 flag instead of -O3 while building libsnappyjava.so

### ISSUE THREAD

**Issue by palladium-coder** [xerial/snappy-java#506]
Hello,

I am curious to know why we are building libsnappyjava.so using [-O2 flag](https://github.com/xerial/snappy-java/blob/98b22256fe4ed00ccaadd2dac98b1622563cc50b/Makefile.common#L98) instead of -O3

**Comment by xerial** [comment]
Using -O3 tends to have compilation issues. As snappy-java need to build binary for various OS types, I prefer using an easier option to build.

**Comment by palladium-coder** [comment]
@xerial Thanks for the information
