### ISSUE TITLE
[Question] Is snappy-java v1.1.10.3 using snappy 1.1.10 ?

### ISSUE THREAD

**Issue by palladium-coder** [xerial/snappy-java#507]
Hello,

I would like to know if we are actually using snappy 1.1.10 . I am asking this because in the [Makefile](https://github.com/xerial/snappy-java/blob/98b22256fe4ed00ccaadd2dac98b1622563cc50b/Makefile#L17) I see that we are using the commit hash of 1.1.8 instead of the commit hash of [1.1.10](https://github.com/google/snappy/commits/1.1.10) which is dc05e026488865bc69313a68bcc03ef2e4ea8e83

**Comment by xerial** [comment]
Good catch. Let me check

**Comment by palladium-coder** [comment]
Hello,

Thanks for looking into this. Is it possible to create a release with the new changes ?

**Comment by palladium-coder** [comment]
@xerial Thanks for creating the release
