### ISSUE TITLE
Is 1.1.x backward compatible with 1.0.x？

### ISSUE THREAD

**Issue by gangxie112** [xerial/snappy-java#522]
Hi，
We want to upgrade the snapp-java from 1.0.x to 1.1.10，but concern about the compatibility. 
According to my understanding:
1. data compressed by 1.1.x could not be decompressed by 1.0.x (Non Framing APIs)
2. data compressed by 1.0.x could be decompressed by 1.1.x  (Non Framing APIs)
Is that right?

thanks

**Comment by gangxie112** [comment]
After some tests，it seems that the compressing apis are compatible between 1.0.5 and 1.1.10.
But not sure why someother report the compatibility issue: https://stackoverflow.com/questions/63185644/compress-and-uncompress-using-different-version-of-snappy-java-library

**Comment by xerial** [comment]
Snappy format itself has not been changed. 

The framing format is a new addition to the snappy, and it's different from the regular snappy format. See https://github.com/xerial/snappy-java#compatibility-notes
