### ISSUE TITLE
Solaris x86_64 native library are missing

### ISSUE THREAD

**Issue by gdchamal** [xerial/snappy-java#55]
Hello,

I have the same problem than one related in issue #42 when running a jvm with -d64 flag on a solaris x86 host.

Native library for architecture reported as amd64 are not present in the snappy distribution. I tried to add this architecture .so files after compiling snappy
in 64 bits mode but encounter another error that I wasn't able to solve at this time.

[P]zen:/tmp# java -d64 -cp ".:./snappy-java-1.0.5-patch-amd64.jar" Main
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.xerial.snappy.SnappyNative.maxCompressedLength(I)I
        at org.xerial.snappy.SnappyNative.maxCompressedLength(Native Method)
        at org.xerial.snappy.Snappy.maxCompressedLength(Snappy.java:320)
        at org.xerial.snappy.Snappy.rawCompress(Snappy.java:333)
        at org.xerial.snappy.Snappy.compress(Snappy.java:92)
        at Main.main(Main.java:10)

**Comment by thirumal** [comment]
I can make time to build both 64-bit and 32-bit libraries for AIX, would you be able to add support for it as well?

**Comment by xerial** [comment]
@thirumal 
Great. Please send a pull request that includes native libraries (.so) for AIX.

**Comment by zapstar** [comment]
I've moved out of IBM, I no longer have access to any AIX machines. Sorry I cannot contribute in this regard.

**Comment by anuragsingh0107** [comment]
how to build org/xerial/snappy/native/SunOS/sparcv9/libsnappyjava.so ?

**Comment by evan912** [comment]
I have similar error while running Apache Spark on Solaris 11 sparc server, error caused by : 

org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=SunOS and os.arch=sparcv9
