### ISSUE TITLE
please update snappyjava.so to 1.1.2!

### ISSUE THREAD

**Issue by Qinwroks** [xerial/snappy-java#87]
google update snappy to 1.1.2, Will snappy-java update snappy.so?

**Comment by bokken** [comment]
As I look at the [commits](https://github.com/google/snappy/commits/master) made to the google snappy project, the only changes in 1.1.2 appear to be documentation in the framing format reserving specific flags for padding and around testing files used in benchmarking. As best I can tell there is no actual runtime impact at all.

**Comment by xerial** [comment]
@bokken 
Thanks for the information. So we can move to 1.1.2 without recompiling binaries.

**Comment by bokken** [comment]
As best I can tell, there is no point in moving to 1.2.
It may be worth clarifying with the Google snappy team.
